version: '3'
networks:
  encurtador:
    driver: bridge
services:
  #######################################
  # Mongo: Banco para os serviços
  #######################################
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    networks:
      - encurtador

  app:
    depends_on:
      - nginx
    container_name: app
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtador

  app2:
    depends_on:
      - nginx
    container_name: app2
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtador

  app3:
    depends_on:
      - nginx
    container_name: app3
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtador

  app4:
    depends_on:
      - nginx
    container_name: app4
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtado

  app5:
    depends_on:
      - nginx
    container_name: app5
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtador

  nginx:
    container_name: load_balance
    image: nginx:alpine
    restart: always
    volumes:
    - "./nginx/:/etc/nginx/conf.d/:ro"
    networks:
      - encurtador
    ports:
      - "80:80"
