version: '3'
networks:
  encurtador:
    driver: bridge
services:
  #######################################
  # Mongo: Banco para os serviços
  #######################################
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    networks:
      - encurtador
    ports:
      - "27017:27017"

  aplicacaco:
    depends_on:
      - nginx
    container_name: aplicacao
    build:
      context: .
      args:
        - img=webdevops/php-apache:7.4
    restart: on-failure
    networks:
      - encurtador
    ports:
      - "8088:80"
      - "44388:443"

  nginx:
    container_name: load_balance
    image: nginx:alpine
    restart: always
    volumes:
    - "./nginx/:/etc/nginx/conf.d/:ro"
    networks:
      - encurtador
    ports:
      - "80:80"
